# Generated by Django 4.0.3 on 2022-07-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longUrl', models.CharField(max_length=500)),
                ('shortUrl', models.CharField(max_length=15)),
            ],
        ),
    ]
