# Generated by Django 4.0.3 on 2022-07-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_link_longurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='longUrl',
            field=models.CharField(default='damm', max_length=500),
            preserve_default=False,
        ),
    ]
